name: PR Noise Detector

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npx jest scripts/detectNoise.test.js

  detect-noise:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v4

      - name: Run PR Noise Detection script
        run: node scripts/detectNoise.js

      - name: Comment on PR with noise results
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const noiseOutput = fs.readFileSync('noise.txt', 'utf8');

            if (noiseOutput.includes("⚠️")) {
                github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: noiseOutput
                });
            }